





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;


namespace ScWebApi.Domain.Models
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        string Url { get;}

		[SitecoreInfo(SitecoreInfoType.Name)]
        string Name { get;}

		[SitecoreField("__Sortorder")]
        int Sortorder { get;}

		[SitecoreInfo(SitecoreInfoType.BaseTemplateIds)]
        IEnumerable<Guid> BaseTemplateIds { get; } 

        [SitecoreInfo(SitecoreInfoType.ContentPath)]
        string ContentPath { get; }

        [SitecoreInfo(SitecoreInfoType.DisplayName)]
        string DisplayName { get; }

        [SitecoreInfo(SitecoreInfoType.FullPath)]
        string FullPath { get; }

        [SitecoreInfo(SitecoreInfoType.Path)]
        string Path { get; }

        [SitecoreInfo(SitecoreInfoType.TemplateId)]
        Guid TemplateId { get; }

        [SitecoreInfo(SitecoreInfoType.TemplateName)]
        string TemplateName { get; }

        [SitecoreChildren(InferType = true)]
        IEnumerable<IGlassBase> Children { get; }

        [SitecoreParent(InferType = true)]
        IGlassBase Parent { get; }
	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }

		[SitecoreInfo(SitecoreInfoType.Name)]
        public virtual string Name { get; private set; }

		[SitecoreField("__Sortorder")]
        public virtual int Sortorder { get; private set; }

        [SitecoreInfo(SitecoreInfoType.BaseTemplateIds)]
        public virtual IEnumerable<Guid> BaseTemplateIds { get; private set; }

        [SitecoreInfo(SitecoreInfoType.ContentPath)]
        public virtual string ContentPath { get; private set; }

        [SitecoreInfo(SitecoreInfoType.DisplayName)]
        public virtual string DisplayName { get; private set; }

        [SitecoreInfo(SitecoreInfoType.FullPath)]
        public virtual string FullPath { get; private set; }

        [SitecoreInfo(SitecoreInfoType.Path)]
        public virtual string Path { get; private set; }

        [SitecoreInfo(SitecoreInfoType.TemplateId)]
        public virtual Guid TemplateId { get; private set; }

        [SitecoreInfo(SitecoreInfoType.TemplateName)]
        public virtual string TemplateName { get; private set; }

        [SitecoreChildren(InferType = true)]
        public virtual IEnumerable<IGlassBase> Children { get; private set; }

        [SitecoreParent(InferType = true)]
        public virtual IGlassBase Parent { get; private set; }
	}
}
namespace ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Pages
{


 	/// <summary>
	/// IProducts_Landing_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Pages/Products Landing Page</para>	
	/// <para>ID: 0c2b9a8f-bd8a-469c-801f-760732e2dd87</para>	
	/// </summary>
	[SitecoreType(TemplateId=IProducts_Landing_PageConstants.TemplateIdString )] //, Cachable = true
	public partial interface IProducts_Landing_Page : IGlassBase , global::ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Pages.IGeneric_Page
	{
				/// <summary>
			/// The Product Categories Folder field.
			/// <para></para>
			/// <para>Field Type: Droptree</para>		
			/// <para>Field ID: 5ea51def-6e1a-420a-9eed-aa487904f4d7</para>
			/// <para>Custom Data: </para>
			/// </summary>
				[SitecoreField(IProducts_Landing_PageConstants.Product_Categories_FolderFieldName)]
		Guid Product_Categories_Folder  {get; set;}
		
	}


	public static partial class IProducts_Landing_PageConstants{

			public const string TemplateIdString = "0c2b9a8f-bd8a-469c-801f-760732e2dd87";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Products Landing Page";

					
			public static readonly ID Product_Categories_FolderFieldId = new ID("5ea51def-6e1a-420a-9eed-aa487904f4d7");
			public const string Product_Categories_FolderFieldName = "Product Categories Folder";
			
			

	}

	
	/// <summary>
	/// Products_Landing_Page
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Pages/Products Landing Page</para>	
	/// <para>ID: 0c2b9a8f-bd8a-469c-801f-760732e2dd87</para>	
	/// </summary>
	[SitecoreType(TemplateId=IProducts_Landing_PageConstants.TemplateIdString)] //, Cachable = true
	public partial class Products_Landing_Page  : GlassBase, IProducts_Landing_Page 
	{
	   
				/// <summary>
		/// The Product Categories Folder field.
		/// <para></para>
		/// <para>Field Type: Droptree</para>		
		/// <para>Field ID: 5ea51def-6e1a-420a-9eed-aa487904f4d7</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
			[SitecoreField(IProducts_Landing_PageConstants.Product_Categories_FolderFieldName)]
		public virtual Guid Product_Categories_Folder  {get; set;}
			
	}
}
namespace ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Shared_Content.Folders
{


 	/// <summary>
	/// IProduct_Categories_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Shared Content/Folders/Product Categories Folder</para>	
	/// <para>ID: 17021883-71e7-491c-aa09-214a7ae6f9b2</para>	
	/// </summary>
	[SitecoreType(TemplateId=IProduct_Categories_FolderConstants.TemplateIdString )] //, Cachable = true
	public partial interface IProduct_Categories_Folder : IGlassBase , global::ScWebApi.Domain.Models.sitecore.templates.Common.IFolder
	{
				/// <summary>
			/// The Category Name field.
			/// <para></para>
			/// <para>Field Type: Single-Line Text</para>		
			/// <para>Field ID: 6908ebf7-d1c5-457b-89f7-ab4a219adad3</para>
			/// <para>Custom Data: </para>
			/// </summary>
				[SitecoreField(IProduct_Categories_FolderConstants.Category_NameFieldName)]
		string Category_Name  {get; set;}
		
	}


	public static partial class IProduct_Categories_FolderConstants{

			public const string TemplateIdString = "17021883-71e7-491c-aa09-214a7ae6f9b2";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Product Categories Folder";

					
			public static readonly ID Category_NameFieldId = new ID("6908ebf7-d1c5-457b-89f7-ab4a219adad3");
			public const string Category_NameFieldName = "Category Name";
			
			

	}

	
	/// <summary>
	/// Product_Categories_Folder
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Shared Content/Folders/Product Categories Folder</para>	
	/// <para>ID: 17021883-71e7-491c-aa09-214a7ae6f9b2</para>	
	/// </summary>
	[SitecoreType(TemplateId=IProduct_Categories_FolderConstants.TemplateIdString)] //, Cachable = true
	public partial class Product_Categories_Folder  : GlassBase, IProduct_Categories_Folder 
	{
	   
				/// <summary>
		/// The Category Name field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 6908ebf7-d1c5-457b-89f7-ab4a219adad3</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
			[SitecoreField(IProduct_Categories_FolderConstants.Category_NameFieldName)]
		public virtual string Category_Name  {get; set;}
			
	}
}
namespace ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Shared_Content.Items
{


 	/// <summary>
	/// IProduct_Category Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Shared Content/Items/Product Category</para>	
	/// <para>ID: 18b6da2e-d40a-42c5-b01b-59aeab4d64e9</para>	
	/// </summary>
	[SitecoreType(TemplateId=IProduct_CategoryConstants.TemplateIdString )] //, Cachable = true
	public partial interface IProduct_Category : IGlassBase , global::ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Shared_Content.Items.Base.IBase_Named_Imported_Content
	{
	
	}


	public static partial class IProduct_CategoryConstants{

			public const string TemplateIdString = "18b6da2e-d40a-42c5-b01b-59aeab4d64e9";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Product Category";

					
			public static readonly ID Legacy_NameFieldId = new ID("7446c4d9-01e7-406c-98d0-8a123ae10c02");
			public const string Legacy_NameFieldName = "Legacy Name";
			
					
			public static readonly ID Legacy_IDFieldId = new ID("fd67f821-6ee0-40c4-bd89-f9ca376416f9");
			public const string Legacy_IDFieldName = "Legacy ID";
			
			

	}

	
	/// <summary>
	/// Product_Category
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Shared Content/Items/Product Category</para>	
	/// <para>ID: 18b6da2e-d40a-42c5-b01b-59aeab4d64e9</para>	
	/// </summary>
	[SitecoreType(TemplateId=IProduct_CategoryConstants.TemplateIdString)] //, Cachable = true
	public partial class Product_Category  : GlassBase, IProduct_Category 
	{
	   
				/// <summary>
		/// The Legacy Name field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 7446c4d9-01e7-406c-98d0-8a123ae10c02</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
			[SitecoreField(IProduct_CategoryConstants.Legacy_NameFieldName)]
		public virtual string Legacy_Name  {get; set;}
				/// <summary>
		/// The Legacy ID field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: fd67f821-6ee0-40c4-bd89-f9ca376416f9</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
			[SitecoreField(IProduct_CategoryConstants.Legacy_IDFieldName)]
		public virtual string Legacy_ID  {get; set;}
			
	}
}
namespace ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Pages
{


 	/// <summary>
	/// IImporter_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Pages/Importer Page</para>	
	/// <para>ID: 26632c3b-28aa-4293-b093-ab30597410f0</para>	
	/// </summary>
	[SitecoreType(TemplateId=IImporter_PageConstants.TemplateIdString )] //, Cachable = true
	public partial interface IImporter_Page : IGlassBase , global::ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Pages.IGeneric_Page
	{
				/// <summary>
			/// The Product Categories Folder field.
			/// <para></para>
			/// <para>Field Type: Droptree</para>		
			/// <para>Field ID: 1bb4a2a9-d818-48b9-a175-76420a836531</para>
			/// <para>Custom Data: </para>
			/// </summary>
				[SitecoreField(IImporter_PageConstants.Product_Categories_FolderFieldName)]
		Guid Product_Categories_Folder  {get; set;}
					/// <summary>
			/// The Products Landing Page field.
			/// <para></para>
			/// <para>Field Type: Droptree</para>		
			/// <para>Field ID: eb284bb6-5749-43f0-8fe4-81056a325057</para>
			/// <para>Custom Data: </para>
			/// </summary>
				[SitecoreField(IImporter_PageConstants.Products_Landing_PageFieldName)]
		Guid Products_Landing_Page  {get; set;}
		
	}


	public static partial class IImporter_PageConstants{

			public const string TemplateIdString = "26632c3b-28aa-4293-b093-ab30597410f0";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Importer Page";

					
			public static readonly ID Product_Categories_FolderFieldId = new ID("1bb4a2a9-d818-48b9-a175-76420a836531");
			public const string Product_Categories_FolderFieldName = "Product Categories Folder";
			
					
			public static readonly ID Products_Landing_PageFieldId = new ID("eb284bb6-5749-43f0-8fe4-81056a325057");
			public const string Products_Landing_PageFieldName = "Products Landing Page";
			
			

	}

	
	/// <summary>
	/// Importer_Page
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Pages/Importer Page</para>	
	/// <para>ID: 26632c3b-28aa-4293-b093-ab30597410f0</para>	
	/// </summary>
	[SitecoreType(TemplateId=IImporter_PageConstants.TemplateIdString)] //, Cachable = true
	public partial class Importer_Page  : GlassBase, IImporter_Page 
	{
	   
				/// <summary>
		/// The Product Categories Folder field.
		/// <para></para>
		/// <para>Field Type: Droptree</para>		
		/// <para>Field ID: 1bb4a2a9-d818-48b9-a175-76420a836531</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
			[SitecoreField(IImporter_PageConstants.Product_Categories_FolderFieldName)]
		public virtual Guid Product_Categories_Folder  {get; set;}
				/// <summary>
		/// The Products Landing Page field.
		/// <para></para>
		/// <para>Field Type: Droptree</para>		
		/// <para>Field ID: eb284bb6-5749-43f0-8fe4-81056a325057</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
			[SitecoreField(IImporter_PageConstants.Products_Landing_PageFieldName)]
		public virtual Guid Products_Landing_Page  {get; set;}
			
	}
}
namespace ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Pages
{


 	/// <summary>
	/// IHome_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Pages/Home Page</para>	
	/// <para>ID: 2ea24ac9-11c9-4f0b-8f2a-b889733e06e8</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHome_PageConstants.TemplateIdString )] //, Cachable = true
	public partial interface IHome_Page : IGlassBase 
	{
	
	}


	public static partial class IHome_PageConstants{

			public const string TemplateIdString = "2ea24ac9-11c9-4f0b-8f2a-b889733e06e8";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Home Page";

			

	}

	
	/// <summary>
	/// Home_Page
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Pages/Home Page</para>	
	/// <para>ID: 2ea24ac9-11c9-4f0b-8f2a-b889733e06e8</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHome_PageConstants.TemplateIdString)] //, Cachable = true
	public partial class Home_Page  : GlassBase, IHome_Page 
	{
	   
			
	}
}
namespace ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Pages
{


 	/// <summary>
	/// ISearch_Results_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Pages/Search Results Page</para>	
	/// <para>ID: 3e0b62fd-0da8-4e57-9c28-8d127febdfa5</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISearch_Results_PageConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISearch_Results_Page : IGlassBase , global::ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Pages.IGeneric_Page
	{
	
	}


	public static partial class ISearch_Results_PageConstants{

			public const string TemplateIdString = "3e0b62fd-0da8-4e57-9c28-8d127febdfa5";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Search Results Page";

			

	}

	
	/// <summary>
	/// Search_Results_Page
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Pages/Search Results Page</para>	
	/// <para>ID: 3e0b62fd-0da8-4e57-9c28-8d127febdfa5</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISearch_Results_PageConstants.TemplateIdString)] //, Cachable = true
	public partial class Search_Results_Page  : GlassBase, ISearch_Results_Page 
	{
	   
			
	}
}
namespace ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Shared_Content.Items.Base
{


 	/// <summary>
	/// IBase_Named_Imported_Content Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Shared Content/Items/Base/Base Named Imported Content</para>	
	/// <para>ID: 63b33824-c0cd-41f5-95d1-5b8f4e76b603</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBase_Named_Imported_ContentConstants.TemplateIdString )] //, Cachable = true
	public partial interface IBase_Named_Imported_Content : IGlassBase , global::ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Shared_Content.Items.Base.IBase_Imported_Content
	{
				/// <summary>
			/// The Legacy Name field.
			/// <para></para>
			/// <para>Field Type: Single-Line Text</para>		
			/// <para>Field ID: 7446c4d9-01e7-406c-98d0-8a123ae10c02</para>
			/// <para>Custom Data: </para>
			/// </summary>
				[SitecoreField(IBase_Named_Imported_ContentConstants.Legacy_NameFieldName)]
		string Legacy_Name  {get; set;}
		
	}


	public static partial class IBase_Named_Imported_ContentConstants{

			public const string TemplateIdString = "63b33824-c0cd-41f5-95d1-5b8f4e76b603";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Base Named Imported Content";

					
			public static readonly ID Legacy_NameFieldId = new ID("7446c4d9-01e7-406c-98d0-8a123ae10c02");
			public const string Legacy_NameFieldName = "Legacy Name";
			
					
			public static readonly ID Legacy_IDFieldId = new ID("fd67f821-6ee0-40c4-bd89-f9ca376416f9");
			public const string Legacy_IDFieldName = "Legacy ID";
			
			

	}

	
	/// <summary>
	/// Base_Named_Imported_Content
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Shared Content/Items/Base/Base Named Imported Content</para>	
	/// <para>ID: 63b33824-c0cd-41f5-95d1-5b8f4e76b603</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBase_Named_Imported_ContentConstants.TemplateIdString)] //, Cachable = true
	public partial class Base_Named_Imported_Content  : GlassBase, IBase_Named_Imported_Content 
	{
	   
				/// <summary>
		/// The Legacy Name field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 7446c4d9-01e7-406c-98d0-8a123ae10c02</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
			[SitecoreField(IBase_Named_Imported_ContentConstants.Legacy_NameFieldName)]
		public virtual string Legacy_Name  {get; set;}
				/// <summary>
		/// The Legacy ID field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: fd67f821-6ee0-40c4-bd89-f9ca376416f9</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
			[SitecoreField(IBase_Named_Imported_ContentConstants.Legacy_IDFieldName)]
		public virtual string Legacy_ID  {get; set;}
			
	}
}
namespace ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Pages
{


 	/// <summary>
	/// IGeneric_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Pages/Generic Page</para>	
	/// <para>ID: 9d0bb4a7-cf91-4e66-bf35-6b384115887c</para>	
	/// </summary>
	[SitecoreType(TemplateId=IGeneric_PageConstants.TemplateIdString )] //, Cachable = true
	public partial interface IGeneric_Page : IGlassBase 
	{
	
	}


	public static partial class IGeneric_PageConstants{

			public const string TemplateIdString = "9d0bb4a7-cf91-4e66-bf35-6b384115887c";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Generic Page";

			

	}

	
	/// <summary>
	/// Generic_Page
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Pages/Generic Page</para>	
	/// <para>ID: 9d0bb4a7-cf91-4e66-bf35-6b384115887c</para>	
	/// </summary>
	[SitecoreType(TemplateId=IGeneric_PageConstants.TemplateIdString)] //, Cachable = true
	public partial class Generic_Page  : GlassBase, IGeneric_Page 
	{
	   
			
	}
}
namespace ScWebApi.Domain.Models.sitecore.templates.Common
{


 	/// <summary>
	/// IFolder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Common/Folder</para>	
	/// <para>ID: a87a00b1-e6db-45ab-8b54-636fec3b5523</para>	
	/// </summary>
	[SitecoreType(TemplateId=IFolderConstants.TemplateIdString )] //, Cachable = true
	public partial interface IFolder : IGlassBase 
	{
	
	}


	public static partial class IFolderConstants{

			public const string TemplateIdString = "a87a00b1-e6db-45ab-8b54-636fec3b5523";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Folder";

			

	}

	
	/// <summary>
	/// Folder
	/// <para></para>
	/// <para>Path: /sitecore/templates/Common/Folder</para>	
	/// <para>ID: a87a00b1-e6db-45ab-8b54-636fec3b5523</para>	
	/// </summary>
	[SitecoreType(TemplateId=IFolderConstants.TemplateIdString)] //, Cachable = true
	public partial class Folder  : GlassBase, IFolder 
	{
	   
			
	}
}
namespace ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Shared_Content.Items.Base
{


 	/// <summary>
	/// IBase_Imported_Content Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Shared Content/Items/Base/Base Imported Content</para>	
	/// <para>ID: b90e201a-510d-4d07-b737-da3073f01a43</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBase_Imported_ContentConstants.TemplateIdString )] //, Cachable = true
	public partial interface IBase_Imported_Content : IGlassBase 
	{
				/// <summary>
			/// The Legacy ID field.
			/// <para></para>
			/// <para>Field Type: Single-Line Text</para>		
			/// <para>Field ID: fd67f821-6ee0-40c4-bd89-f9ca376416f9</para>
			/// <para>Custom Data: </para>
			/// </summary>
				[SitecoreField(IBase_Imported_ContentConstants.Legacy_IDFieldName)]
		string Legacy_ID  {get; set;}
		
	}


	public static partial class IBase_Imported_ContentConstants{

			public const string TemplateIdString = "b90e201a-510d-4d07-b737-da3073f01a43";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Base Imported Content";

					
			public static readonly ID Legacy_IDFieldId = new ID("fd67f821-6ee0-40c4-bd89-f9ca376416f9");
			public const string Legacy_IDFieldName = "Legacy ID";
			
			

	}

	
	/// <summary>
	/// Base_Imported_Content
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Shared Content/Items/Base/Base Imported Content</para>	
	/// <para>ID: b90e201a-510d-4d07-b737-da3073f01a43</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBase_Imported_ContentConstants.TemplateIdString)] //, Cachable = true
	public partial class Base_Imported_Content  : GlassBase, IBase_Imported_Content 
	{
	   
				/// <summary>
		/// The Legacy ID field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: fd67f821-6ee0-40c4-bd89-f9ca376416f9</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
			[SitecoreField(IBase_Imported_ContentConstants.Legacy_IDFieldName)]
		public virtual string Legacy_ID  {get; set;}
			
	}
}
namespace ScWebApi.Domain.Models.sitecore.templates.Common
{


 	/// <summary>
	/// ISite Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Common/Site</para>	
	/// <para>ID: d5ac3876-9430-47c3-b7f2-5c15c3b35ae3</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISite : IGlassBase 
	{
	
	}


	public static partial class ISiteConstants{

			public const string TemplateIdString = "d5ac3876-9430-47c3-b7f2-5c15c3b35ae3";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Site";

			

	}

	
	/// <summary>
	/// Site
	/// <para></para>
	/// <para>Path: /sitecore/templates/Common/Site</para>	
	/// <para>ID: d5ac3876-9430-47c3-b7f2-5c15c3b35ae3</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteConstants.TemplateIdString)] //, Cachable = true
	public partial class Site  : GlassBase, ISite 
	{
	   
			
	}
}
namespace ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Shared_Content.Items
{


 	/// <summary>
	/// IProduct Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Shared Content/Items/Product</para>	
	/// <para>ID: eabfa294-654e-4985-8ec7-2346dd9cf458</para>	
	/// </summary>
	[SitecoreType(TemplateId=IProductConstants.TemplateIdString )] //, Cachable = true
	public partial interface IProduct : IGlassBase , global::ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Shared_Content.Items.Base.IBase_Named_Imported_Content
	{
				/// <summary>
			/// The Description field.
			/// <para></para>
			/// <para>Field Type: Rich Text</para>		
			/// <para>Field ID: f5986ea5-fe57-42ef-bf88-2da1efc17e2e</para>
			/// <para>Custom Data: </para>
			/// </summary>
				[SitecoreField(IProductConstants.DescriptionFieldName)]
		string Description  {get; set;}
					/// <summary>
			/// The List Price field.
			/// <para></para>
			/// <para>Field Type: Single-Line Text</para>		
			/// <para>Field ID: 9ef63b75-4678-4eee-9db6-64d9389ee318</para>
			/// <para>Custom Data: </para>
			/// </summary>
				[SitecoreField(IProductConstants.List_PriceFieldName)]
		string List_Price  {get; set;}
					/// <summary>
			/// The Product Subcategory field.
			/// <para></para>
			/// <para>Field Type: Droptree</para>		
			/// <para>Field ID: 23cf718c-b33c-4667-84f7-4060daa289e6</para>
			/// <para>Custom Data: </para>
			/// </summary>
				[SitecoreField(IProductConstants.Product_SubcategoryFieldName)]
		Guid Product_Subcategory  {get; set;}
		
	}


	public static partial class IProductConstants{

			public const string TemplateIdString = "eabfa294-654e-4985-8ec7-2346dd9cf458";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Product";

					
			public static readonly ID DescriptionFieldId = new ID("f5986ea5-fe57-42ef-bf88-2da1efc17e2e");
			public const string DescriptionFieldName = "Description";
			
					
			public static readonly ID List_PriceFieldId = new ID("9ef63b75-4678-4eee-9db6-64d9389ee318");
			public const string List_PriceFieldName = "List Price";
			
					
			public static readonly ID Product_SubcategoryFieldId = new ID("23cf718c-b33c-4667-84f7-4060daa289e6");
			public const string Product_SubcategoryFieldName = "Product Subcategory";
			
					
			public static readonly ID Legacy_NameFieldId = new ID("7446c4d9-01e7-406c-98d0-8a123ae10c02");
			public const string Legacy_NameFieldName = "Legacy Name";
			
					
			public static readonly ID Legacy_IDFieldId = new ID("fd67f821-6ee0-40c4-bd89-f9ca376416f9");
			public const string Legacy_IDFieldName = "Legacy ID";
			
			

	}

	
	/// <summary>
	/// Product
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Shared Content/Items/Product</para>	
	/// <para>ID: eabfa294-654e-4985-8ec7-2346dd9cf458</para>	
	/// </summary>
	[SitecoreType(TemplateId=IProductConstants.TemplateIdString)] //, Cachable = true
	public partial class Product  : GlassBase, IProduct 
	{
	   
				/// <summary>
		/// The Description field.
		/// <para></para>
		/// <para>Field Type: Rich Text</para>		
		/// <para>Field ID: f5986ea5-fe57-42ef-bf88-2da1efc17e2e</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
			[SitecoreField(IProductConstants.DescriptionFieldName)]
		public virtual string Description  {get; set;}
				/// <summary>
		/// The List Price field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 9ef63b75-4678-4eee-9db6-64d9389ee318</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
			[SitecoreField(IProductConstants.List_PriceFieldName)]
		public virtual string List_Price  {get; set;}
				/// <summary>
		/// The Product Subcategory field.
		/// <para></para>
		/// <para>Field Type: Droptree</para>		
		/// <para>Field ID: 23cf718c-b33c-4667-84f7-4060daa289e6</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
			[SitecoreField(IProductConstants.Product_SubcategoryFieldName)]
		public virtual Guid Product_Subcategory  {get; set;}
				/// <summary>
		/// The Legacy Name field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: 7446c4d9-01e7-406c-98d0-8a123ae10c02</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
			[SitecoreField(IProductConstants.Legacy_NameFieldName)]
		public virtual string Legacy_Name  {get; set;}
				/// <summary>
		/// The Legacy ID field.
		/// <para></para>
		/// <para>Field Type: Single-Line Text</para>		
		/// <para>Field ID: fd67f821-6ee0-40c4-bd89-f9ca376416f9</para>
		/// <para>Custom Data: </para>
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
			[SitecoreField(IProductConstants.Legacy_IDFieldName)]
		public virtual string Legacy_ID  {get; set;}
			
	}
}
