





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;


namespace ScWebApi.Domain.Models
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; set; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; set; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        string Url { get; set; }

		[SitecoreInfo(SitecoreInfoType.Name)]
        string Name { get; set; }

		[SitecoreField("__Sortorder")]
        int Sortorder { get; set; }

		[SitecoreInfo(SitecoreInfoType.BaseTemplateIds)]
        IEnumerable<Guid> BaseTemplateIds { get; set; }

        [SitecoreInfo(SitecoreInfoType.ContentPath)]
        string ContentPath { get; set; }

        [SitecoreInfo(SitecoreInfoType.DisplayName)]
        string DisplayName { get; set; }

        [SitecoreInfo(SitecoreInfoType.FullPath)]
        string FullPath { get; set; }

        [SitecoreInfo(SitecoreInfoType.Path)]
        string Path { get; set; }

        [SitecoreInfo(SitecoreInfoType.TemplateId)]
        Guid TemplateId { get; set; }

        [SitecoreInfo(SitecoreInfoType.TemplateName)]
        string TemplateName { get; set; }

        [SitecoreChildren(InferType = true)]
        IEnumerable<IGlassBase> Children { get; set; }

        [SitecoreParent(InferType = true)]
        IGlassBase Parent { get; set; }
	}
}
namespace ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Pages
{


 	/// <summary>
	/// IProducts_Landing_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Pages/Products Landing Page</para>	
	/// <para>ID: 0c2b9a8f-bd8a-469c-801f-760732e2dd87</para>	
	/// </summary>
	[SitecoreType(TemplateId=IProducts_Landing_Page_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IProducts_Landing_Page : IGlassBase , global::ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Pages.IGeneric_Page
	{
			
					/// <summary>
			/// The Product Categories Folder field.
			/// <para></para>
			/// <para>Field Type: Droptree</para>		
			/// <para>Field ID: 5ea51def-6e1a-420a-9eed-aa487904f4d7</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IProducts_Landing_Page_Constants.Product_Categories_Folder_FieldName)]
						Guid Product_Categories_Folder  { get; set; }
				}

	public static partial class IProducts_Landing_Page_Constants{

			public const string TemplateIdString = "0c2b9a8f-bd8a-469c-801f-760732e2dd87";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Products Landing Page";

					
			public static readonly Guid Product_Categories_Folder_FieldId = new Guid("5ea51def-6e1a-420a-9eed-aa487904f4d7");
			public const string Product_Categories_Folder_FieldName = "Product Categories Folder";
			
			

	}


}
namespace ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Shared_Content.Folders
{


 	/// <summary>
	/// IProduct_Categories_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Shared Content/Folders/Product Categories Folder</para>	
	/// <para>ID: 17021883-71e7-491c-aa09-214a7ae6f9b2</para>	
	/// </summary>
	[SitecoreType(TemplateId=IProduct_Categories_Folder_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IProduct_Categories_Folder : IGlassBase , global::ScWebApi.Domain.Models.sitecore.templates.Common.IFolder
	{
			
					/// <summary>
			/// The Category Name field.
			/// <para></para>
			/// <para>Field Type: Single-Line Text</para>		
			/// <para>Field ID: 6908ebf7-d1c5-457b-89f7-ab4a219adad3</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IProduct_Categories_Folder_Constants.Category_Name_FieldName)]
						string Category_Name  { get; set; }
				}

	public static partial class IProduct_Categories_Folder_Constants{

			public const string TemplateIdString = "17021883-71e7-491c-aa09-214a7ae6f9b2";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Product Categories Folder";

					
			public static readonly Guid Category_Name_FieldId = new Guid("6908ebf7-d1c5-457b-89f7-ab4a219adad3");
			public const string Category_Name_FieldName = "Category Name";
			
			

	}


}
namespace ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Shared_Content.Items
{


 	/// <summary>
	/// IProduct_Category Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Shared Content/Items/Product Category</para>	
	/// <para>ID: 18b6da2e-d40a-42c5-b01b-59aeab4d64e9</para>	
	/// </summary>
	[SitecoreType(TemplateId=IProduct_Category_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IProduct_Category : IGlassBase , global::ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Shared_Content.Items.Base.IBase_Named_Imported_Content
	{
		}

	public static partial class IProduct_Category_Constants{

			public const string TemplateIdString = "18b6da2e-d40a-42c5-b01b-59aeab4d64e9";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Product Category";

					
			public static readonly Guid Legacy_Name_FieldId = new Guid("7446c4d9-01e7-406c-98d0-8a123ae10c02");
			public const string Legacy_Name_FieldName = "Legacy Name";
			
					
			public static readonly Guid Legacy_ID_FieldId = new Guid("fd67f821-6ee0-40c4-bd89-f9ca376416f9");
			public const string Legacy_ID_FieldName = "Legacy ID";
			
			

	}


}
namespace ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Pages
{


 	/// <summary>
	/// IImporter_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Pages/Importer Page</para>	
	/// <para>ID: 26632c3b-28aa-4293-b093-ab30597410f0</para>	
	/// </summary>
	[SitecoreType(TemplateId=IImporter_Page_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IImporter_Page : IGlassBase , global::ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Pages.IGeneric_Page
	{
			
					/// <summary>
			/// The Product Categories Folder field.
			/// <para></para>
			/// <para>Field Type: Droptree</para>		
			/// <para>Field ID: 1bb4a2a9-d818-48b9-a175-76420a836531</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IImporter_Page_Constants.Product_Categories_Folder_FieldName)]
						Guid Product_Categories_Folder  { get; set; }
					
					/// <summary>
			/// The Products Landing Page field.
			/// <para></para>
			/// <para>Field Type: Droptree</para>		
			/// <para>Field ID: eb284bb6-5749-43f0-8fe4-81056a325057</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IImporter_Page_Constants.Products_Landing_Page_FieldName)]
						Guid Products_Landing_Page  { get; set; }
				}

	public static partial class IImporter_Page_Constants{

			public const string TemplateIdString = "26632c3b-28aa-4293-b093-ab30597410f0";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Importer Page";

					
			public static readonly Guid Product_Categories_Folder_FieldId = new Guid("1bb4a2a9-d818-48b9-a175-76420a836531");
			public const string Product_Categories_Folder_FieldName = "Product Categories Folder";
			
					
			public static readonly Guid Products_Landing_Page_FieldId = new Guid("eb284bb6-5749-43f0-8fe4-81056a325057");
			public const string Products_Landing_Page_FieldName = "Products Landing Page";
			
			

	}


}
namespace ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Pages
{


 	/// <summary>
	/// IHome_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Pages/Home Page</para>	
	/// <para>ID: 2ea24ac9-11c9-4f0b-8f2a-b889733e06e8</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHome_Page_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IHome_Page : IGlassBase 
	{
		}

	public static partial class IHome_Page_Constants{

			public const string TemplateIdString = "2ea24ac9-11c9-4f0b-8f2a-b889733e06e8";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Home Page";

			

	}


}
namespace ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Pages
{


 	/// <summary>
	/// ISearch_Results_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Pages/Search Results Page</para>	
	/// <para>ID: 3e0b62fd-0da8-4e57-9c28-8d127febdfa5</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISearch_Results_Page_Constants.TemplateIdString )] //, Cachable = true
	public partial interface ISearch_Results_Page : IGlassBase , global::ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Pages.IGeneric_Page
	{
		}

	public static partial class ISearch_Results_Page_Constants{

			public const string TemplateIdString = "3e0b62fd-0da8-4e57-9c28-8d127febdfa5";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Search Results Page";

			

	}


}
namespace ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Shared_Content.Items.Base
{


 	/// <summary>
	/// IBase_Named_Imported_Content Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Shared Content/Items/Base/Base Named Imported Content</para>	
	/// <para>ID: 63b33824-c0cd-41f5-95d1-5b8f4e76b603</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBase_Named_Imported_Content_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IBase_Named_Imported_Content : IGlassBase , global::ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Shared_Content.Items.Base.IBase_Imported_Content
	{
			
					/// <summary>
			/// The Legacy Name field.
			/// <para></para>
			/// <para>Field Type: Single-Line Text</para>		
			/// <para>Field ID: 7446c4d9-01e7-406c-98d0-8a123ae10c02</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IBase_Named_Imported_Content_Constants.Legacy_Name_FieldName)]
						string Legacy_Name  { get; set; }
				}

	public static partial class IBase_Named_Imported_Content_Constants{

			public const string TemplateIdString = "63b33824-c0cd-41f5-95d1-5b8f4e76b603";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Base Named Imported Content";

					
			public static readonly Guid Legacy_Name_FieldId = new Guid("7446c4d9-01e7-406c-98d0-8a123ae10c02");
			public const string Legacy_Name_FieldName = "Legacy Name";
			
					
			public static readonly Guid Legacy_ID_FieldId = new Guid("fd67f821-6ee0-40c4-bd89-f9ca376416f9");
			public const string Legacy_ID_FieldName = "Legacy ID";
			
			

	}


}
namespace ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Pages
{


 	/// <summary>
	/// IGeneric_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Pages/Generic Page</para>	
	/// <para>ID: 9d0bb4a7-cf91-4e66-bf35-6b384115887c</para>	
	/// </summary>
	[SitecoreType(TemplateId=IGeneric_Page_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IGeneric_Page : IGlassBase 
	{
		}

	public static partial class IGeneric_Page_Constants{

			public const string TemplateIdString = "9d0bb4a7-cf91-4e66-bf35-6b384115887c";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Generic Page";

			

	}


}
namespace ScWebApi.Domain.Models.sitecore.templates.Common
{


 	/// <summary>
	/// IFolder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Common/Folder</para>	
	/// <para>ID: a87a00b1-e6db-45ab-8b54-636fec3b5523</para>	
	/// </summary>
	[SitecoreType(TemplateId=IFolder_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IFolder : IGlassBase 
	{
		}

	public static partial class IFolder_Constants{

			public const string TemplateIdString = "a87a00b1-e6db-45ab-8b54-636fec3b5523";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Folder";

			

	}


}
namespace ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Shared_Content.Items.Base
{


 	/// <summary>
	/// IBase_Imported_Content Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Shared Content/Items/Base/Base Imported Content</para>	
	/// <para>ID: b90e201a-510d-4d07-b737-da3073f01a43</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBase_Imported_Content_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IBase_Imported_Content : IGlassBase 
	{
			
					/// <summary>
			/// The Legacy ID field.
			/// <para></para>
			/// <para>Field Type: Single-Line Text</para>		
			/// <para>Field ID: fd67f821-6ee0-40c4-bd89-f9ca376416f9</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IBase_Imported_Content_Constants.Legacy_ID_FieldName)]
						string Legacy_ID  { get; set; }
				}

	public static partial class IBase_Imported_Content_Constants{

			public const string TemplateIdString = "b90e201a-510d-4d07-b737-da3073f01a43";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Base Imported Content";

					
			public static readonly Guid Legacy_ID_FieldId = new Guid("fd67f821-6ee0-40c4-bd89-f9ca376416f9");
			public const string Legacy_ID_FieldName = "Legacy ID";
			
			

	}


}
namespace ScWebApi.Domain.Models.sitecore.templates.Common
{


 	/// <summary>
	/// ISite Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Common/Site</para>	
	/// <para>ID: d5ac3876-9430-47c3-b7f2-5c15c3b35ae3</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISite_Constants.TemplateIdString )] //, Cachable = true
	public partial interface ISite : IGlassBase 
	{
		}

	public static partial class ISite_Constants{

			public const string TemplateIdString = "d5ac3876-9430-47c3-b7f2-5c15c3b35ae3";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Site";

			

	}


}
namespace ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Shared_Content.Items
{


 	/// <summary>
	/// IProduct Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/ScWebApi/Shared Content/Items/Product</para>	
	/// <para>ID: eabfa294-654e-4985-8ec7-2346dd9cf458</para>	
	/// </summary>
	[SitecoreType(TemplateId=IProduct_Constants.TemplateIdString )] //, Cachable = true
	public partial interface IProduct : IGlassBase , global::ScWebApi.Domain.Models.sitecore.templates.ScWebApi.Shared_Content.Items.Base.IBase_Named_Imported_Content
	{
						/// <summary>
			/// The Description field.
			/// <para></para>
			/// <para>Field Type: Rich Text</para>		
			/// <para>Field ID: f5986ea5-fe57-42ef-bf88-2da1efc17e2e</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IProduct_Constants.Description_FieldName)]
						string Description  { get; set; }

			/// <summary>
			/// The Description field in RAW format.
			/// <para></para>
			/// <para>Field Type: Rich Text</para>		
			/// <para>Field ID: f5986ea5-fe57-42ef-bf88-2da1efc17e2e</para>
			/// <para>Custom Data: </para>
			/// </summary>
										//[SitecoreField(IProduct_Constants.Description_FieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
						//string Description_Raw  { get; set; }
		
					
					/// <summary>
			/// The List Price field.
			/// <para></para>
			/// <para>Field Type: Single-Line Text</para>		
			/// <para>Field ID: 9ef63b75-4678-4eee-9db6-64d9389ee318</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IProduct_Constants.List_Price_FieldName)]
						string List_Price  { get; set; }
					
					/// <summary>
			/// The Product Subcategory field.
			/// <para></para>
			/// <para>Field Type: Droptree</para>		
			/// <para>Field ID: 23cf718c-b33c-4667-84f7-4060daa289e6</para>
			/// <para>Custom Data: </para>
			/// </summary>
										[SitecoreField(IProduct_Constants.Product_Subcategory_FieldName)]
						Guid Product_Subcategory  { get; set; }
				}

	public static partial class IProduct_Constants{

			public const string TemplateIdString = "eabfa294-654e-4985-8ec7-2346dd9cf458";
			public static readonly Guid TemplateId = new Guid(TemplateIdString);
			public const string TemplateName = "Product";

					
			public static readonly Guid Description_FieldId = new Guid("f5986ea5-fe57-42ef-bf88-2da1efc17e2e");
			public const string Description_FieldName = "Description";
			
					
			public static readonly Guid List_Price_FieldId = new Guid("9ef63b75-4678-4eee-9db6-64d9389ee318");
			public const string List_Price_FieldName = "List Price";
			
					
			public static readonly Guid Product_Subcategory_FieldId = new Guid("23cf718c-b33c-4667-84f7-4060daa289e6");
			public const string Product_Subcategory_FieldName = "Product Subcategory";
			
					
			public static readonly Guid Legacy_Name_FieldId = new Guid("7446c4d9-01e7-406c-98d0-8a123ae10c02");
			public const string Legacy_Name_FieldName = "Legacy Name";
			
					
			public static readonly Guid Legacy_ID_FieldId = new Guid("fd67f821-6ee0-40c4-bd89-f9ca376416f9");
			public const string Legacy_ID_FieldName = "Legacy ID";
			
			

	}


}
